#!/usr/bin/env python3

import sys
from declarecli import DeclarativeCommands, DeclarativeOptions, DeclarativeCLI
from syspy import Shell
sh = Shell()

version = 'Version: 0.0.1'

synopsis = '''\
Usage: ./ops <--option|-o> <command>
tools to manage adium integration pipeline and testing'''

class CLI(DeclarativeCLI):
    __level__ = 0
    class Synopsis:
        @staticmethod
        def body(): print(synopsis)

    class Options(DeclarativeOptions):
        class help_h:
            description = 'extended help message of this package'
            @staticmethod
            def instructions():
                cli.extended_help()
                sys.exit(0)
        class updateDependencies_u:
            description = 'update all dependencies for the project'
            @staticmethod
            def instructions():
                if not sh.exists('./env'):
                    sh.command('virtualenv env', passFail=True)
                sh.command('./scripts/update_dependencies.sh', passFail=True)
                sh.finish()
        class verbose_v:
            description = 'get more descriptive command output'
            @staticmethod
            def instructions():
                sh.verbose = True
        class version:
            description = 'output the current tool version'
            @staticmethod
            def instructions():
                print(version)
                sys.exit(0)

    class Commands(DeclarativeCommands):
        class build:
            description = 'create project by pulling dependencies'
            @staticmethod
            def instructions(remainder):
                from scripts.build import build_ublock
                build_ublock(sh)
        class load:
            description = 'run the extension in chromium (kills all instances of chromium)'
            @staticmethod
            def instructions(remainder):
                sh.command('./scripts/load.sh &')
        class test:
            description = 'run integration integration_tests for uBlock'
            @staticmethod
            def instructions(remainder):
                from tests.ublock_tests import IntegrationTests
                chromedriver_path = sh.respond(['which', 'chromedriver']).strip()
                i_tests = IntegrationTests(chromedriver_path)
                rtn = i_tests.run_tests()
                print(rtn)

        def __default_no_args__(self):
            cli.help()

cli = CLI()
cli.run(sys.argv[1:])
sh.finish()